package com.shuham.cineflow_kmp.di

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.shuham.cineflow_kmp.data.local.AppDatabase
import kotlinx.cinterop.ExperimentalForeignApi
import platform.Foundation.NSDocumentDirectory
import platform.Foundation.NSFileManager
import platform.Foundation.NSUserDomainMask
import org.koin.dsl.module
import io.ktor.client.engine.HttpClientEngine
import io.ktor.client.engine.darwin.Darwin

@OptIn(ExperimentalForeignApi::class)
actual val platformModule = module {
    single<AppDatabase> {
        // 1. Get the path to the iOS Documents directory
        val documentDirectory = NSFileManager.defaultManager.URLForDirectory(
            directory = NSDocumentDirectory,
            inDomain = NSUserDomainMask,
            appropriateForURL = null,
            create = false,
            error = null
        )

        // 2. Append the database filename
        val dbFilePath = requireNotNull(documentDirectory?.path) + "/cineflow.db"

        // 3. Create the builder using the iOS specific factory
        Room.databaseBuilder<AppDatabase>(
            name = dbFilePath,
            //factory = { AppDatabase::class.instantiateImpl() } // Auto-generated by KSP
        )
            .setDriver(BundledSQLiteDriver())
            .fallbackToDestructiveMigration(true)
            .build()
    }

    single<HttpClientEngine> { Darwin.create() }
}